"""alter fisddsdds

Revision ID: 0440de77e899
Revises: a715f9422f61
Create Date: 2026-09-14 06:47:08.927523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0440de77e899'
down_revision: Union[str, Sequence[str], None] = 'a715f9422f61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('test', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
