"""alter field test from Album

Revision ID: 2b03e19cf505
Revises: 9fbec70605bf
Create Date: 2026-09-14 06:39:43.052115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2b03e19cf505'
down_revision: Union[str, Sequence[str], None] = '9fbec70605bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('test', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album', 'test')
    # ### end Alembic commands ###
