"""alter fisddsddssdswdssddd

Revision ID: 9acfb32826a5
Revises: 78465f0e8416
Create Date: 2026-09-14 06:43:29.697654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9acfb32826a5'
down_revision: Union[str, Sequence[str], None] = '78465f0e8416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('test', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
