"""delete test field

Revision ID: 9d9ce1ab11ec
Revises: b24a8ff45bb0
Create Date: 2026-09-14 07:12:48.688008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d9ce1ab11ec'
down_revision: Union[str, Sequence[str], None] = 'b24a8ff45bb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('test', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
