"""alter field test fromsss

Revision ID: 9f891005f3dd
Revises: 2b03e19cf505
Create Date: 2026-09-14 06:40:38.792032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f891005f3dd'
down_revision: Union[str, Sequence[str], None] = '2b03e19cf505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('test', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
