"""remove field test from Album

Revision ID: 9fbec70605bf
Revises: d894d844347c
Create Date: 2026-09-14 06:39:22.916787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fbec70605bf'
down_revision: Union[str, Sequence[str], None] = 'd894d844347c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('test', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
