"""add test field to song

Revision ID: 4ee8f5d6bdc9
Revises: 7b32ebbba02b
Create Date: 2026-09-13 07:00:50.373137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ee8f5d6bdc9'
down_revision: Union[str, Sequence[str], None] = '7b32ebbba02b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
