"""add test field to song table

Revision ID: cb5a33cb553f
Revises: 4ee8f5d6bdc9
Create Date: 2026-09-13 07:01:43.686095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'cb5a33cb553f'
down_revision: Union[str, Sequence[str], None] = '4ee8f5d6bdc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('test', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'test')
    # ### end Alembic commands ###
